### ISSUE TITLE
RSZ different value?

### ISSUE THREAD

**Issue by Taimor-artist** [iceland2k14/rsz#14]
Starting Program...
======================================================================
[Input Index #: 0]
     R: 6d88d6de1c154910d768c5bb857ae79cafe73d8fac3c9b05feaf3674a8a32089
     S: 4f992a212410b69371fa4271095418f9b1621d5cb01a723db3a166f505f12d17
     Z: 5da587be81bfeedfbf17ad8a4927a1b698601a78d53ffbf9ea7402f4f4ab8a2b
PubKey: 035f41af49a08af0b4051951e80fa80e61825b933dffc092e2f5fb486c5ae93321
======================================================================
[Input Index #: 1]
     R: 00adb8b26048cc4e3c2ed85b3203af413cdbfa1cabefb9499b5c1ab5964857e9eb
     S: 2c20e458daf8078141dcd1acd13f5ae0307182214208c1cbaadf7d4b056b12e6
     Z: 45aab64359449ead09fb3bb158642a621923c465b5d54920b3c43c534b2ac6e1
PubKey: 03c1f06c71bc2888e47f4eb35a3ef3cf0e434947911a1ed1b81f2a7ad1e4d90b9c

**Comment by Taimor-artist** [comment]
can someone help me to teach.

**Comment by zackrider-png** [comment]
I will teach you but send me the address
