### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by Govagents** [iceland2k14/rsz#33]
Practicing using yours here and.....

~/Downloads/rsz$ python3 getz_input.py -rawtx 01000000028370ef64eb83519fd14f9d74826059b4ce00eae33b5473629486076c5b3bf215000000008c4930460221009bf436ce1f12979ff47b4671f16b06a71e74269005c19178384e9d267e50bbe9022100c7eabd8cf796a78d8a7032f99105cdcb1ae75cd8b518ed4efe14247fb00c9622014104e3896e6cabfa05a332368443877d826efc7ace23019bd5c2bc7497f3711f009e873b1fcc03222f118a6ff696efa9ec9bb3678447aae159491c75468dcc245a6cffffffffb0385cd9a933545628469aa1b7c151b85cc4a087760a300e855af079eacd25c5000000008b48304502210094b12a2dd0f59b3b4b84e6db0eb4ba4460696a4f3abf5cc6e241bbdb08163b45022007eaf632f320b5d9d58f1e8d186ccebabea93bad4a6a282a3c472393fe756bfb014104e3896e6cabfa05a332368443877d826efc7ace23019bd5c2bc7497f3711f009e873b1fcc03222f118a6ff696efa9ec9bb3678447aae159491c75468dcc245a6cffffffff01404b4c00000000001976a91402d8103ac969fe0b92ba04ca8007e729684031b088ac00000000

Starting Program...
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acer/Downloads/rsz/getz_input.py", line 115, in <module>
    e = getSignableTxn(m)
  File "/home/acer/Downloads/rsz/getz_input.py", line 95, in getSignableTxn
    e += '1976a914' + HASH160(inp_list[one][4]) + '88ac'
  File "/home/acer/Downloads/rsz/getz_input.py", line 105, in HASH160
    return hashlib.new('ripemd160', hashlib.sha256(bytes.fromhex(pubk_hex)).digest() ).hexdigest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160

what did I do wrong here? I already install your secp256k1 library using
~/Downloads/rsz$ pip3 install secp256k1
so, any idea what went wrong here bud? I'm using linux mint, thanks before hand.

**Comment by iceland2k14** [comment]
You need to copy those 3 files. No need to install using pip.
Try latest update. hashlib dependency is removed.

**Comment by Govagents** [comment]
It worked, thanks 4 the knowledge and incredible coding man 👍.

**Comment by Govagents** [comment]
It worked, thanks 4 the knowledge and incredible coding man 👍.

**Comment by Govagents** [comment]
It worked, thanks 4 the knowledge and incredible coding man 👍.
