### ISSUE TITLE
Help me to get this code 

### ISSUE THREAD

**Issue by Ankithuuuu** [iceland2k14/rsz#7]
Please watch the video so that you guys can easily understand the video link in below, can you guys please help me find forge.py code ( with this forge.py we can easily find private key) [ this is forging technique for k ]
https://vimeo.com/694404329

**Comment by bigvito19** [comment]
> forge.py

I watched the video and I looked at the video description. I see he is selling that code and I also notice he was using @iceland2k14 code right along with his.
